class Conclusion

  def self.good
    [
      "Potential customers might find this ad intriguing.",
      "This advertisement may catch the eye of interested buyers.",
      "The audience could potentially be captivated by this ad.",
      "This advertisement seems potentially appealing to viewers.",
      "Interested parties might find this ad worth their time.",
      "The ad could potentially resonate with the intended audience.",
      "Potential customers may find this ad compelling and informative.",
      "The audience might be interested in what this ad has to offer.",
      "This ad could potentially spark the interest of prospective buyers.",
      "The audience would likely find this ad engaging and informative.",
      "Potential customers might be intrigued by the content of this ad.",
      "This advertisement would potentially be of interest to the target audience.",
      "The ad might be appealing to individuals looking for this type of product.",
      "Interested parties would likely find this ad informative and useful.",
      "Potential customers may appreciate the value proposition presented in this ad.",
      "The audience could potentially find this ad informative and persuasive.",
      "This advertisement might resonate with the target audience and generate interest.",
      "Viewers might be interested in exploring more about the product advertised.",
      "Potential customers might find the ad interesting and worth sharing with others.",
      "The ad could potentially generate a positive response from the target audience.",
      "It's possible that users will find the ad compelling.",
      "The ad may be appealing to users.",
      "The ad has potential to capture users' attention.",
      "It's possible that users will find the ad interesting.",
      "The ad has elements that could be engaging for users.",
      "The ad seems to have a certain appeal to it.",
      "The ad could be interesting to certain users.",
      "It's possible that the ad will resonate with users.",
      "The ad appears to have some interesting features.",
      "Some users may find the ad to be worth considering.",
      "The ad may be able to generate some interest among users.",
      "The ad has a chance of being intriguing to its target audience.",
      "It's possible that users may find the ad informative.",
      "The ad seems to have the potential to be engaging.",
      "Users may find the ad to be intriguing for various reasons.",
      "The ad has some interesting aspects that could appeal to users.",
      "It's possible that the ad will be perceived as interesting by its intended audience."
    ]
  end
  
  def self.bad
    [
      "This ad may not appeal to everyone.",
      "Some viewers may not find this ad compelling.",
      "This advertisement may not resonate with everyone.",
      "Not everyone may be interested in this ad.",
      "This ad may not be of interest to some users.",
      "Some viewers may not appreciate this advertisement.",
      "This ad may not capture the attention of all users.",
      "Not all viewers may find this ad engaging.",
      "Some users may not be attracted to this ad.",
      "This advertisement may not be for everyone.",
      "Not everyone may like this ad.",
      "Some viewers may find this advertisement uninteresting.",
      "This ad may not be everyone's cup of tea.",
      "Not all users may be drawn to this advertisement.",
      "Some viewers may not be impressed by this ad.",
      "This ad may not strike a chord with everyone.",
      "Not all users may find this ad appealing.",
      "Some users may not be intrigued by this ad.",
      "This advertisement may not be everyone's favorite.",
      "Not everyone may enjoy this ad.",
      "People may not like the ad.",
      "The ad may not be very engaging for users.",
      "Users may not find the ad to be very interesting.",
      "It's possible that users may not be interested in the ad.",
      "The ad has elements that could be unappealing to users.",
      "Users may not be drawn to the ad.",
      "The ad appears to be unremarkable in terms of user engagement.",
      "The ad seems to be lacking in terms of user interest.",
      "Users may not be impressed with the ad's content.",
      "The ad may not resonate with users in the intended way.",
      "It's possible that users may find the ad to be uninspiring.",
      "It's possible that users may find the ad to be forgettable.",
      "Users may not be interested in what the ad has to offer.",
      "It's possible that users may not find the ad to be compelling enough."
    ]
  end

end