good_generic_descriptions = [
	"The description is expertly penned, with exceptional attention to detail.",
	"The writer has woven an intricate and captivating description.",
	"The description is a testament to the writer's literary prowess.",
	"The words used in the description evoke vivid imagery and emotion.",
	"The author has artfully crafted a descriptive masterpiece.",
	"The description flows effortlessly, engaging the reader with every word.",
	"The writer has skillfully painted a picture with their words.",
	"The description is flawlessly written, leaving no detail overlooked.",
	"The writer's use of language in the description is simply stunning.",
	"The description is a shining example of exquisite writing.",
	"The description is expertly articulated, showcasing the author's talent.",
	"The writer has skillfully crafted a detailed and immersive description.",
	"The language used in the description is rich and evocative.",
	"The description is masterfully constructed, with impeccable grammar and syntax.",
	"The author has painted a vivid and captivating picture with their words.",
	"The writer has a remarkable ability to convey imagery through description.",
	"The description is written with an unparalleled level of precision and finesse.",
	"The writer's use of figurative language in the description is sublime.",
	"The description is a tour de force of eloquent prose.",
	"The author's writing style in the description is both engaging and poetic.",
	"The writer has successfully captured the essence of the subject in their description.",
	"The description is beautifully written, with a sense of artistry and grace.",
	"The author has a remarkable talent for crafting descriptive passages that transport the reader.",
	"The writer's command of language in the description is truly impressive.",
	"The description is a captivating work of literary art.",
	"The author has a keen eye for detail and a gift for descriptive writing.",
	"The description is a testament to the writer's creativity and skill.",
	"The writer's use of sensory language in the description is particularly effective.",
	"The description is an exceptional example of the power of words to create imagery.",
	"The author has a rare ability to create a sense of atmosphere through their descriptions.",
	"The writer has a talent for crafting descriptive prose that is both elegant and engaging.",
	"The description is a beautifully rendered portrait of the subject, captured in words.",
	"The author has a gift for creating images in the reader's mind through their writing.",
	"The writer's use of language in the description is masterful and precise.",
	"The description is a testament to the writer's skill and creativity.",
	"The author's ability to paint a picture with words is truly impressive.",
	"The description is a shining example of the writer's literary prowess.",
	"The writer's skillful use of sensory details in the description is outstanding.",
	"The author's command of language in the description is simply breathtaking.",
	"The description is a work of art, skillfully crafted with words.",
	"The author has a gift for making even the most mundane details come alive with their writing.",
	"The description is an immersive experience that leaves the reader feeling like they've been transported to another world.",
	"The writer's use of metaphors and similes in the description is truly remarkable.",
	"The description is a testament to the writer's ability to create a sense of place and atmosphere through their words.",
	"The author has an uncanny ability to evoke emotions through their writing.",
	"The description is a captivating journey through the subject, with every detail expertly captured.",
	"The writer's descriptive prose is like a symphony, each word working together in perfect harmony.",
	"The description is a masterpiece of sensory language, with every detail carefully chosen to create a vivid picture.",
	"The author's use of imagery in the description is both powerful and evocative.",
	"The writer has crafted a description that is both informative and engaging.",
	"The description is a tour de force of descriptive writing, showcasing the author's talent and skill.",
	"The writer's ability to create tension and suspense through their description is exceptional.",
	"The description is an impressive display of the writer's ability to evoke mood and atmosphere through their words.",
	"The author's writing is a testament to the power of language to create a sense of wonder and awe.",
	"The description is a captivating glimpse into the subject, with every detail expertly rendered.",
	"The writer has created a description that is both poetic and insightful.",
	"The description is a testament to the writer's ability to paint a picture with words, leaving a lasting impression on the reader.",
	"The author's use of descriptive language is so vivid, the reader can almost smell, taste, and feel the subject.",
	"The description is a work of art, each sentence crafted with care and precision.",
	"The writer's ability to capture the essence of the subject through their writing is truly remarkable."
]
good_product_descriptions = [
  "The author has done a great job of highlighting the key features of the product in a clear and concise manner.",
  "The writer's attention to detail in describing the product's features is truly impressive.",
  "The product description is a masterclass in how to effectively showcase product features.",
  "The writer has expertly demonstrated how each product feature is unique and adds value to the overall experience.",
  "The product description is a comprehensive and informative guide to all the features offered.",
  "The writer's use of descriptive language in highlighting product features is both engaging and informative.",
  "The product description is a prime example of how to effectively communicate the benefits of each feature.",
  "The author has skillfully woven together the product features to create a compelling picture of the overall product.",
  "The writer's ability to articulate the features in a way that is easy to understand is truly remarkable.",
  "The product description showcases the full range of features available in an engaging and informative way.",
  "The author has taken a complex set of features and presented them in a way that is easy to digest.",
  "The writer has done a fantastic job of highlighting the unique selling points of each feature.",
  "The product description is a must-read for anyone looking to understand the full range of features offered.",
  "The author's ability to clearly explain the features of the product is commendable.",
  "The writer has done an excellent job of showcasing how each feature adds value to the overall product.",
  "The product description is a comprehensive guide to all the features offered, presented in a clear and concise manner.",
  "The author has expertly highlighted the most important features of the product, making it easy for the reader to understand.",
  "The writer's use of real-world examples to explain the features is both effective and engaging.",
  "The product description is a treasure trove of information on the features and benefits of the product.",
  "The author has skillfully presented each feature in a way that is easy to understand and appreciate.",
  "The writer has taken the time to showcase each feature in its own right, highlighting its unique benefits.",
  "The product description is a testament to the writer's ability to showcase features in a way that resonates with the reader.",
  "The author has created a compelling narrative around the product features, making it easy for the reader to see the value in each one.",
  "The writer has done an excellent job of presenting the features in a way that is both informative and engaging.",
  "The product description is a comprehensive guide to all the features offered, presented in a way that is easy to follow.",
  "The author has taken great care to explain each feature in a way that is accessible to all readers.",
  "The writer's use of analogies to explain the features is both effective and entertaining.",
  "The product description is a great example of how to showcase product features in a way that resonates with the target audience.",
  "The author has expertly presented the features in a way that highlights their unique benefits.",
  "The writer's attention to detail in presenting the product features is truly admirable.",
  "The product description is a valuable resource for anyone looking to understand the features of the product.",
  "The author has successfully conveyed the value of each feature, making it easy for the reader to appreciate the product as a whole.",
  "The writer has done an excellent job of showcasing how the features work together to create a seamless user experience.",
  "The product description is a comprehensive guide to all the features offered, presented in a way"
]	
good_offer_descriptions = [
	"The description does a great job of highlighting the lucrative offers available to customers.",
	"The writer has expertly showcased the enticing offers in a way that is sure to capture the reader's attention.",
	"The product description masterfully outlines the incredible value that customers can get through the offers provided.",
	"The author has done a remarkable job of presenting the lucrative offers in a way that is easy to understand and appreciate.",
	"The writer's attention to detail in describing the offers is truly impressive.",
	"The product description is a great example of how to effectively communicate the benefits of the lucrative offers.",
	"The author has skillfully woven together the various offers to create an enticing picture of the overall value proposition.",
	"The writer's use of persuasive language in describing the offers is both engaging and effective.",
	"The product description is a must-read for anyone looking to take advantage of the incredible offers provided.",
	"The author has done an excellent job of presenting each offer in a lucid way.",
	"The writer's ability to articulate the offers in a way that is easy to understand is truly remarkable.",
	"The product description showcases the full range of lucrative offers available in a compelling and informative way.",
	"The author has taken a complex set of offers and presented them in a way that is easy to digest.",
	"The writer has done a fantastic job of highlighting the unique selling points of each offer.",
	"The product description is a comprehensive and informative guide to all the lucrative offers provided.",
	"The author's ability to clearly explain the offers is commendable.",
	"The writer has done an excellent job of showcasing how each offer adds value to the overall product.",
	"The product description is a valuable resource for anyone looking to take advantage of the lucrative offers.",
	"The author has expertly highlighted the most important offers, making it easy for the reader to understand the benefits.",
	"The product description is a treasure trove of information on the lucrative offers available.",
	"The author has skillfully presented each offer in a way that is easy to understand and appreciate.",
	"The writer has taken the time to showcase each offer in its own right, highlighting its unique benefits.",
	"The product description is a testament to the writer's ability to showcase offers in a way that resonates with the reader.",
	"The author has created a compelling narrative around the lucrative offers, making it easy for the reader to see the value in each one.",
	"The writer has done an excellent job of presenting the offers in a way that is both informative and engaging.",
	"The product description is a comprehensive guide to all the lucrative offers provided, presented in a way that is easy to follow.",
	"The product description is a great example of how to showcase lucrative offers in a way that resonates with the target audience.",
	"The author has expertly presented the offers in a way that highlights their unique benefits.",
	"The writer's attention to detail in presenting the lucrative offers is truly admirable.",
	"The author has successfully conveyed the value of each offer, making it easy for the reader to appreciate the product as a whole.",
	"The writer has done an excellent job of showcasing how the offers work together to create an incredible value proposition for customers.",
	"The product description is an informative and persuasive guide to the lucrative offers available.",
	"The author's ability to present the offers in a way that is easy to understand and appreciate is truly impressive.",
	"The writer has effectively conveyed the value of the offers in a way that is sure to capture the reader's attention.",
	"The author has successfully conveyed the value of each offer, making it easy for the reader to appreciate the product as a whole."
]
bad_short_descriptions = [
  "The description is poorly written and lacks detail.",
  "The brief product description fails to provide any meaningful information.",
  "The product description is insufficient and lacks clarity.",
  "The author's attempt at describing the product is unconvincing and lacks substance.",
  "The description is unimpressive, offering little insight into the product's features.",
  "The description is disappointingly brief and fails to provide a comprehensive overview of the product.",
  "The author's attempt at describing the product is lackluster and fails to do it justice.",
  "The product description is weak and lacks the necessary details to make an informed decision.",
  "The author's writing is uninspired, resulting in a description that is both uninformative and unappealing.",
  "The description is insufficient, leaving the reader with more questions than answers.",
  "The author's lack of attention to detail has resulted in a description that is both vague and uninteresting.",
  "The product description is lacking in substance, failing to provide the reader with a clear understanding of what the product offers.",
  "The author's attempt at describing the product is half-hearted, resulting in a description that is both weak and unconvincing.",
  "The description is cursory and fails to capture the essence of the product.",
  "The author's writing lacks creativity, resulting in a description that is both unremarkable and forgettable.",
  "The product description is lackadaisical and does not adequately convey the product's benefits.",
  "The author's failure to provide a thorough description of the product leaves the reader wondering what they are missing.",
  "The brief description is underwhelming and fails to convey the product's unique selling points."
]
bad_absent_descriptions = [
  "The product listing lacks description.",
  "The product is listed without any accompanying description.",
  "No description of the product is provided.",
  "The product is presented without a written description.",
  "The description section is blank, offering no details about the product.",
  "The seller has failed to include any description of the product in the listing.",
  "The absence of a product description leaves potential buyers in the dark.",
  "The product is listed without any accompanying text or product description.",
  "The product is presented without any written description.",
  "The listing is devoid of any descriptive text about the product.",
  "There is no explanation or description given for the product being sold.",
  "The product is listed with no accompanying details or written information.",
  "The product is not described in any way, shape, or form in the description.",
  "The product's features and benefits are not communicated in the listing through description.",
  "The listing fails to provide any details or description of the product.",
  "The absence of a product description leaves potential buyers uninformed and uncertain about the product being sold."
]
bad_emojis_descriptions = [
  "The description is peppered with odd and perplexing emojis.",
  "The presence of bizarre emojis detracts from the clarity of the description.",
  "The product description is littered with unconventional and confusing emojis.",
  "The use of atypical and peculiar emojis in the description is off-putting.",
  "The presence of strange and nonsensical emojis in the description is distracting.",
  "The use of unusual and bewildering emojis makes the description hard to comprehend.",
  "The presence of weird and enigmatic emojis in the description is confounding.",
  "The inclusion of unconventional and inexplicable emojis makes the description unclear.",
  "The use of strange and outlandish emojis in the description is jarring.",
  "The presence of atypical and perplexing emojis in the description is disorienting.",
  "The description is riddled with bewildering and off-kilter emojis.",
  "The use of eccentric and mysterious emojis in the description is unsettling.",
  "The presence of weird and unconventional emojis in the description is disconcerting.",
  "The description is filled with puzzling and peculiar emojis.",
  "The use of bizarre and confounding emojis in the description is perplexing.",
  "The presence of cryptic and unusual emojis in the description is mystifying.",
  "The use of non-standard and quirky emojis in the description is unusual.",
  "The description is marred by strange and inexplicable emojis that hinder comprehension.",
  "The use of uncommon and puzzling emojis in the description is confounding.",
  "The presence of odd and surreal emojis in the description is perplexing."
]
