class Description
	
	def self.good_generic
		[
			"The description is skillfully written, with exceptional attention to detail.",
			"The writer has expertly crafted a captivating and intricate description.",
			"The description showcases the writer's mastery of language and storytelling.",
			"The words used in the description evoke vivid imagery and deep emotions.",
			"The author has masterfully composed a descriptive masterpiece.",
			"The description flows smoothly, captivating the reader with its every word.",
			"The writer has artfully depicted a vivid picture through their descriptive language.",
			"The description is flawlessly executed, leaving no detail unattended.",
			"The writer's use of language in the description is stunning and captivating.",
			"The description is a brilliant display of exquisite writing.",
			"The description is articulated with expertise, showcasing the author's immense talent.",
			"The writer has skillfully constructed a detailed and immersive description.",
			"The language employed in the description is rich and evocative.",
			"The description is a masterpiece of meticulous construction, demonstrating impeccable grammar and syntax.",
			"The author has painted a vibrant and captivating image with their words.",
			"The writer possesses an exceptional ability to convey imagery through their descriptive prowess.",
			"The description is written with unparalleled precision and finesse.",
			"The writer's use of figurative language in the description is exceptionally sublime.",
			"The description is a remarkable example of eloquent prose and artistry.",
			"The author's writing style in the description is engaging and poetic.",
			"The writer successfully captures the essence of the subject in their detailed description.",
			"The description is beautifully composed, exuding artistry and grace.",
			"The author possesses a remarkable talent for crafting descriptive passages that transport the reader.",
			"The writer exhibits a command of language in the description that is truly impressive.",
			"The description is a captivating work of literary artistry.",
			"The author has a keen eye for detail and a gift for descriptive storytelling.",
			"The description stands as a testament to the writer's creativity and skill.",
			"The writer's use of sensory language in the description is particularly effective and immersive.",
			"The description exemplifies the extraordinary power of words to create vivid imagery.",
			"The author possesses a rare ability to create a sense of atmosphere through their descriptions.",
			"The writer has a talent for crafting descriptive prose that is both elegant and engaging.",
			"The description is a beautifully rendered portrait of the subject, expertly captured in words.",
			"The author has a gift for conjuring vivid images in the reader's mind through their eloquent writing.",
			"The writer's use of language in the description is masterful, displaying precision and artistry.",
			"The description serves as a testament to the writer's skill and creativity.",
			"The author's ability to paint a rich picture with words is truly impressive.",
			"The description is a shining example of the writer's literary aptitude.",
			"The writer's skillful use of sensory details in the description is outstanding and immersive.",
			"The author's command of language in the description is simply breathtaking.",
			"The description is a work of art, skillfully crafted with meticulous wordsmithing.",
			"The author possesses the gift of bringing even the most mundane details to life through their writing.",
			"The description offers an immersive experience that transports the reader to another world.",
			"The writer's use of metaphors and similes in the description is truly remarkable and evocative.",
			"The description exemplifies the writer's ability to create a vivid sense of place and atmosphere through their words.",
			"The author has an uncanny ability to evoke emotions through their descriptive writing.",
			"The description takes the reader on a captivating journey through the subject, expertly capturing every detail.",
			"The writer's descriptive prose is akin to a symphony, with each word harmonizing perfectly.",
			"The description is a masterpiece of sensory language, where every carefully chosen detail creates a vivid tapestry.",
			"The author's use of imagery in the description is both powerful and evocative.",
			"The writer has crafted a description that is both informative and enthralling.",
			"The description serves as a testament to the writer's talent and skill, leaving a lasting impact.",
			"The writer's ability to create tension and suspense through their description is exceptional and gripping.",
			"The description is an impressive display of the writer's ability to evoke mood and atmosphere through their words.",
			"The author's writing is a testament to the power of language to create a sense of wonder and awe.",
			"The description offers a captivating glimpse into the subject, with every detail expertly captured.",
			"The writer has created a description that is both poetic and insightful in its narrative.",
			"The description is a testament to the writer's ability to paint a picture with words, leaving an indelible impression on the reader.",
			"The author's use of descriptive language is so vivid that the reader can almost smell, taste, and feel the subject.",
			"The description is a work of art, with each sentence meticulously crafted with care and precision.",
			"The writer's ability to capture the essence of the subject through their writing is truly remarkable."
		]		
	end

	def self.good_product
		[
			"The author has skillfully highlighted the salient features of the product, delivering a clear and concise description.",
			"The writer's meticulous attention to detail in describing the product's features is truly remarkable.",
			"The product description is an exemplar of effectively showcasing the product's features.",
			"The writer has expertly demonstrated the distinctiveness of each product feature and its contribution to the overall user experience.",
			"The product description serves as a comprehensive and informative guide, elucidating all the offered features.",
			"The writer's adept use of descriptive language in accentuating product features is both engaging and informative.",
			"The product description stands as a prime example of effectively communicating the benefits of each feature.",
			"The author has seamlessly woven together the product features, creating a compelling portrayal of the entire product.",
			"The writer's ability to articulate the features in an easily understandable manner is truly noteworthy.",
			"The product description presents the full spectrum of features in an engaging and informative manner.",
			"The author has skillfully simplified a complex set of features, ensuring ease of comprehension.",
			"The writer has done an exceptional job of highlighting the unique selling points of each feature.",
			"The product description is a must-read for anyone seeking a comprehensive understanding of the range of features provided.",
			"The author's ability to elucidate the product's features in a clear manner is commendable.",
			"The writer has excellently showcased how each feature adds value to the overall product.",
			"The product description serves as a comprehensive guide, providing a clear and concise overview of all the offered features.",
			"The author has expertly emphasized the most crucial product features, facilitating reader understanding.",
			"The writer effectively employs real-world examples to elucidate the features, resulting in both effectiveness and engagement.",
			"The product description is a treasure trove of information, offering insights into the features and benefits of the product.",
			"The author skillfully presents each feature in an easily understandable and appreciable way.",
			"The writer has dedicated attention to presenting each feature individually, emphasizing its unique advantages.",
			"The product description stands as a testament to the writer's ability to resonate with readers by effectively showcasing the features.",
			"The author has crafted a compelling narrative around the product features, enabling readers to recognize the value in each one.",
			"The writer has done an excellent job of presenting the features in an informative and engaging manner.",
			"The product description provides a comprehensive and intelligible overview of all the offered features.",
			"The author has taken great care to elucidate each feature, ensuring accessibility for all readers.",
			"The writer effectively uses analogies to explicate the features, resulting in both efficacy and entertainment.",
			"The product description is an outstanding showcase of effectively communicating product features to resonate with the target audience.",
			"The author has expertly presented the features, accentuating their unique benefits.",
			"The writer's meticulous attention to detail in presenting the product features is highly commendable.",
			"The product description serves as a valuable resource for anyone seeking to understand the product's features.",
			"The author has successfully conveyed the value of each feature, making it easy for readers to appreciate the product as a whole.",
			"The writer has done an excellent job of showcasing how the features synergistically create a seamless user experience.",
			"The product description serves as a comprehensive guide, encompassing all the features in a coherent manner."
		]		
	end

	def self.good_offer
		[
			"The description effectively highlights the enticing offers available to customers.",
			"The writer has skillfully presented the captivating offers in a manner that is bound to grab the reader's attention.",
			"The product description expertly outlines the exceptional value that customers can gain from the provided offers.",
			"The author has done a remarkable job of presenting the lucrative offers in an understandable and appreciable way.",
			"The writer's meticulous attention to detail in describing the offers is truly impressive.",
			"The product description serves as a great example of effectively communicating the benefits of the lucrative offers.",
			"The author has skillfully intertwined the various offers, creating an enticing portrayal of the overall value proposition.",
			"The writer effectively employs persuasive language to describe the offers, resulting in engagement and effectiveness.",
			"The product description is a must-read for anyone looking to take advantage of the incredible offers provided.",
			"The author has excellently presented each offer in a clear manner.",
			"The writer's ability to articulate the offers in an understandable way is truly remarkable.",
			"The product description showcases the full range of lucrative offers available in a compelling and informative manner.",
			"The author has simplified a complex set of offers, making them easily digestible.",
			"The writer has done a fantastic job of highlighting the unique selling points of each offer.",
			"The product description is a comprehensive and informative guide to all the lucrative offers provided.",
			"The author's ability to clearly explain the offers is commendable.",
			"The writer has done an excellent job of showcasing how each offer adds value to the overall product.",
			"The product description is a valuable resource for anyone looking to take advantage of the lucrative offers.",
			"The author has expertly highlighted the most important offers, facilitating reader understanding of the benefits.",
			"The product description is a treasure trove of information on the lucrative offers available.",
			"The author has skillfully presented each offer in an understandable and appreciable way.",
			"The writer has taken the time to showcase each offer individually, emphasizing its unique benefits.",
			"The product description is a testament to the writer's ability to showcase offers in a manner that resonates with the reader.",
			"The author has crafted a compelling narrative around the lucrative offers, making it easy for the reader to recognize the value in each one.",
			"The writer has done an excellent job of presenting the offers in an informative and engaging manner.",
			"The product description is a comprehensive guide to all the lucrative offers provided, presented in an easy-to-follow manner.",
			"The product description serves as a great example of effectively showcasing lucrative offers that resonate with the target audience.",
			"The author has expertly presented the offers, highlighting their unique benefits.",
			"The writer's meticulous attention to detail in presenting the lucrative offers is truly admirable.",
			"The author has successfully conveyed the value of each offer, making it easy for the reader to appreciate the product as a whole.",
			"The writer has done an excellent job of showcasing how the offers work together to create an incredible value proposition for customers.",
			"The product description is an informative and persuasive guide to the lucrative offers available.",
			"The author's ability to present the offers in an understandable and appreciable manner is truly impressive.",
			"The writer effectively conveys the value of the offers in a manner that is sure to capture the reader's attention.",
			"The author has successfully conveyed the value of each offer, making it easy for the reader to appreciate the product as a whole."
		]		
	end

	def self.bad_short
		[
			"The description is poorly crafted and lacks sufficient detail.",
			"The concise product description fails to offer any substantial information.",
			"The product description is inadequate and lacks clarity.",
			"The author's portrayal of the product is unconvincing and lacks depth.",
			"The description is unimpressive, providing limited insight into the product's features.",
			"The description is disappointingly brief and fails to provide a comprehensive overview of the product.",
			"The author's attempt at describing the product is lackluster and fails to give it justice.",
			"The product description is weak and lacks the necessary details to make an informed decision.",
			"The author's writing is uninspiring, resulting in a description that is both uninformative and unappealing.",
			"The description is insufficient, leaving the reader with more questions than answers.",
			"The author's lack of attention to detail has resulted in a vague and uninteresting description.",
			"The product description lacks substance, failing to provide the reader with a clear understanding of what the product offers.",
			"The author's attempt at describing the product is half-hearted, resulting in a weak and unconvincing description.",
			"The description is cursory and fails to capture the essence of the product.",
			"The author's writing lacks creativity, resulting in an unremarkable and forgettable description.",
			"The product description is lackadaisical and does not adequately convey the product's benefits.",
			"The author's failure to provide a thorough description of the product leaves the reader wondering what they are missing.",
			"The concise description is underwhelming and fails to communicate the product's unique selling points."
		]		
	end

	def self.bad_absent
		[
			"The product listing lacks any form of description.",
			"The product is listed without any accompanying explanatory text.",
			"No written description is provided for the product.",
			"The product is presented without a descriptive text in the listing.",
			"The description section is empty, providing no information about the product.",
			"The seller has neglected to include any description of the product in the listing.",
			"The absence of a product description leaves potential buyers uninformed.",
			"The product is listed without any accompanying text or description.",
			"The product is presented without any written information or description.",
			"The listing is void of any descriptive text regarding the product.",
			"There is no explanation or description given for the product being sold.",
			"The product is listed without any accompanying details or written information.",
			"The product is not described in any way, shape, or form in the description.",
			"The product's features and benefits are not communicated in the listing through description.",
			"The listing fails to provide any details or description of the product.",
			"The absence of a product description leaves potential buyers uninformed and uncertain about the product being sold."
		]		
	end

	def self.bad_emojis
		[
		  "The description is peppered with odd and perplexing emojis.",
		  "The presence of bizarre emojis detracts from the clarity of the description.",
		  "The product description is littered with unconventional and confusing emojis.",
		  "The use of atypical and peculiar emojis in the description is off-putting.",
		  "The presence of strange and nonsensical emojis in the description is distracting.",
		  "The use of unusual and bewildering emojis makes the description hard to comprehend.",
		  "The presence of weird and enigmatic emojis in the description is confounding.",
		  "The inclusion of unconventional and inexplicable emojis makes the description unclear.",
		  "The use of strange and outlandish emojis in the description is jarring.",
		  "The presence of atypical and perplexing emojis in the description is disorienting.",
		  "The description is riddled with bewildering and off-kilter emojis.",
		  "The use of eccentric and mysterious emojis in the description is unsettling.",
		  "The presence of weird and unconventional emojis in the description is disconcerting.",
		  "The description is filled with puzzling and peculiar emojis.",
		  "The use of bizarre and confounding emojis in the description is perplexing.",
		  "The presence of cryptic and unusual emojis in the description is mystifying.",
		  "The use of non-standard and quirky emojis in the description is unusual.",
		  "The description is marred by strange and inexplicable emojis that hinder comprehension.",
		  "The use of uncommon and puzzling emojis in the description is confounding.",
		  "The presence of odd and surreal emojis in the description is perplexing."
		]
	end

	def self.bad_generic
		[
			"The description is poorly crafted, lacking clarity and coherence in its presentation.",
			"The writing in the description is a jumble of disjointed sentences, making it difficult to understand.",
			"The description is riddled with grammatical errors, indicating a lack of attention to detail.",
			"The author's attempt at describing the product is marred by convoluted and confusing language.",
			"The description reads as if it was hastily put together, lacking structure and coherence.",
			"The writing style in the description is inconsistent and fails to effectively convey the product's features.",
			"The description is an incoherent mess, with fragmented sentences and unclear explanations.",
			"The author's poor command of language is evident in the description, resulting in a confusing narrative.",
			"The description lacks proper organization, making it difficult to follow and understand.",
			"The writing in the description is verbose and wordy, obscuring the key points and information.",
			"The description is filled with excessive jargon and technical terms, alienating potential buyers.",
			"The author's lack of clarity and conciseness in the description leaves readers puzzled and uninformed.",
			"The description is poorly structured, lacking logical flow and coherence in its presentation.",
			"The writing in the description is filled with repetitive phrases and unnecessary details, detracting from its effectiveness.",
			"The author's poor choice of words and awkward phrasing in the description undermines its overall impact.",
			"The description is a hodgepodge of unrelated information, failing to provide a cohesive overview of the product.",
			"The writing style in the description is dry and uninspiring, failing to capture the reader's attention.",
			"The description is overly generic and lacks specific details, making it difficult to differentiate the product.",
			"The author's lack of attention to proper formatting and structure in the description diminishes its readability.",
			"The description is littered with spelling and punctuation errors, indicating a lack of editing and proofreading.",
			"The writing in the description is excessively long-winded, causing readers to lose interest and engagement.",
			"The description fails to evoke any excitement or enthusiasm about the product, leaving it flat and uninteresting.",
			"The author's poor use of descriptive language in the description results in a bland and uninspiring portrayal of the product.",
			"The description lacks a clear focus and fails to highlight the unique selling points of the product effectively.",
			"The writing style in the description is monotonous and lacks any creative flair, making it unmemorable.",
			"The description is overly vague and ambiguous, leaving readers with more questions than answers.",
			"The author's lack of attention to detail and accuracy in the description undermines its credibility and trustworthiness.",
			"The description is laden with excessive adjectives and superlatives, diminishing its authenticity and believability.",
			"The writing in the description is filled with redundant phrases and unnecessary repetitions, detracting from its clarity.",
			"The description lacks a cohesive narrative, with disjointed information and inconsistent messaging throughout."
		]		
	end

end
