class Image
  def self.good_generic_pimage
    [
      "The stunning product image effectively highlights the product's beauty.",
      "The product image possesses such high quality that it appears remarkably lifelike.",
      "The product image perfectly captures the essence of the product, giving it an inviting allure.", 
      "Through its well-composed structure, the product image emanates a genuine sense of style and sophistication.",
      "The product image's remarkable attention to detail prominently showcases the product's craftsmanship.",
      "The visually appealing product image establishes a strong emotional connection with the viewer.",
      "By skillfully employing light and shadow, the product image adds depth and dimension to the product.",
      "The product image's creative composition impressively enhances the product's aesthetic appeal.",
      "The product image's unique perspective offers an intriguing new dimension to the product's features.",
      "With its high resolution, the product image effectively highlights the product's quality and design.",
      "The product image's well-executed color palette perfectly complements the product's design.",
      "The product image's meticulous attention to detail truly highlights the product's quality and craftsmanship.",
      "The product image is flawlessly executed, setting the product apart from the competition.",
      "The product image's distinctive composition captivatingly showcases the product's features.",
      "The product image is expertly framed to accentuate the product's beauty in the most optimal way.",
      "The product image's high-resolution quality further enhances the stunning appearance of the product.",
      "The product image flawlessly captures the essence of the product, forging an emotional connection with the viewer.",
      "The creative composition of the product image elevates the product's aesthetic appeal.",
      "Through a perfect balance of light and shadow, the product image adds depth to the product's features.",
      "The visually pleasing product image instills a strong desire to own the product.",
      "The product image's meticulous attention to detail showcases the product's quality and craftsmanship.",
      "The unique perspective of the product image introduces a fresh dimension to the product's features.",
      "The product image's well-executed color palette complements the product's design, amplifying its appeal.",
      "The meticulously executed product image sets the product apart from the competition.",
      "The product image's impressive attention to detail prominently showcases the product's craftsmanship.",
      "The product image's intriguing perspective adds a new dimension to the product's features.",
      "With its high resolution, the product image effectively highlights the product's quality and design.",
      "The product image's carefully curated color palette perfectly complements the product's design.",
      "The product image's well-composed structure creates a genuine sense of style and sophistication.", 
      "The product image presents the product's beauty in an astonishing manner.",
      "The product image is of such exceptional quality that it appears remarkably realistic.",
      "Capturing the product flawlessly, the image entices viewers with its inviting appeal.",
      "The well-composed product image exudes elegance and sophistication.",
      "Every intricate detail in the product image showcases the craftsmanship with impressive precision.",
      "The visually captivating product image forms a strong emotional bond with the viewer.",
      "Skillful play of light and shadow in the product image adds depth and dimension to the product.",
      "The creatively composed product image significantly enhances the product's aesthetic appeal.",
      "The product image's unique perspective offers a fresh and captivating view of the product's features.",
      "With its outstanding resolution, the product image vividly emphasizes the product's quality and design.",
      "The well-executed color palette in the product image perfectly complements the product's design, enhancing its allure.",
      "The remarkable attention to detail in the product image effectively showcases the product's quality and craftsmanship.",
      "The product image is executed with such finesse that it truly sets the product apart from others.",
      "The distinctive composition of the product image prominently showcases the product's appealing features.",
      "The product image is expertly framed, presenting the product's beauty in the most captivating way.",
      "The high-resolution quality of the product image accentuates the product's stunning appearance.",
      "With its impeccable portrayal, the product image deeply resonates with viewers, forging an emotional connection.",
      "The artistic composition of the product image elevates the product's aesthetic appeal to new heights.",
      "The perfect balance of light and shadow in the product image adds a sense of depth to its features.",
      "The visually pleasing product image evokes a strong desire and aspiration to own the product."
    ]
  end

  def self.good_editing
    [
      "The image has undergone a meticulous editing process with great attention to detail, resulting in a beautifully enhanced and visually captivating composition.",
      "The skilled editor has applied their expertise and refined techniques to flawlessly refine every aspect, seamlessly blending colors, adjusting lighting and contrast, and ensuring every element is perfectly balanced.",
      "Through a meticulous editing process, every detail has been refined, resulting in a visually captivating masterpiece.",
      "The image has been expertly edited, showcasing the editor's keen eye for detail and artistic vision.",
      "A careful editing touch has transformed the image into a visually stunning work of art.",
      "The image has been meticulously edited, resulting in a visually striking and polished final product.",
      "Through skillful editing techniques, the image has been transformed into a visually captivating masterpiece.",
      "The image displays exceptional editing skills, with precise attention to detail and flawless execution.",
      "With careful editing, the image has been elevated to a new level of visual appeal.",
      "The image has undergone a refined editing process, resulting in a polished and visually pleasing composition.",
      "Through meticulous editing, the image has been enhanced to perfection, capturing its true essence.",
      "The image has been skillfully edited, revealing the editor's mastery in refining and enhancing visuals.",
      "An artistic editing approach has transformed the image into a visually mesmerizing and captivating piece.",
      "The image showcases a meticulous editing process, resulting in a flawless and visually stunning composition.",
      "Through expert editing techniques, the image has been refined to achieve a harmonious and striking visual balance.",
      "The image has been carefully edited, showcasing the editor's keen attention to detail and artistic sensibilities.",
      "A masterful editing touch has breathed life into the image, creating a visually arresting masterpiece.",
      "With artistic precision, the image has been meticulously edited to evoke a sense of awe and admiration.",
      "The image has undergone an intricate editing process, resulting in a visually dynamic and engaging composition.",
      "Through skillful editing, the image has been transformed into an alluring and visually captivating work of art.",
      "The image has been thoughtfully edited, capturing the subject's essence with finesse and creativity.",
      "A meticulous editing approach has brought out the image's true beauty, resulting in a visually striking piece.",
      "The image has been skillfully edited, showcasing the editor's mastery in enhancing its visual impact.",
      "With careful attention to detail, the image has been expertly edited to create a visually stunning result.",
      "The image has undergone a refined editing process, resulting in a visually polished and captivating composition.",
      "Through meticulous editing techniques, the image has been transformed into a visually compelling and evocative artwork.",
      "The image displays exceptional editing skills, with precise attention to detail and artistic finesse.",
      "With skillful editing, the image has been elevated to a new level of visual appeal and artistic brilliance.",
      "The image has been expertly edited, showcasing the editor's talent for enhancing visuals and creating aesthetic harmony.",
      "Through meticulous editing, the image has been refined to perfection, capturing its essence with remarkable clarity and beauty.",
      "The image has been skillfully edited, revealing the editor's artistic expertise and exceptional attention to detail."
    ]    
  end

  def self.good_captions_pimage
    [
      "The essence of the product is beautifully captured in the image with an enlightening caption.",
      "The image exhibits skillful editing accompanied by a commendably written caption.",
      "The valuable addition of an informative caption complements the well-edited image.",
      "The image is flawlessly edited, and the caption provides exceptional information.",
      "Crafted with expertise, the image is accompanied by an informative and well-written caption.",
      "The image is skillfully edited, and its accompanying caption eloquently describes the product.",
      "Both the image and its accompanying caption offer informative insights while captivating visually.",
      "The informative and well-written caption matches the attention to detail in the captivating image.",
      "The creatively edited image gains value with the informative caption that enhances it.",
      "The beautifully edited image is complemented by an informative caption that conveys valuable information.",
      "The combination of the image and its informative caption paints a complete picture of the product.",
      "The well-edited image and its informative caption serve as a testament to the product's exceptional quality.",
      "The image is expertly edited, and the accompanying caption provides valuable insights.",
      "The informative caption perfectly complements the beautifully edited image.",
      "The creatively edited image is enhanced by an informative caption that provides insightful information.",
      "The image is skillfully captured, and the informative caption adds value to its content.",
      "The beautifully edited image is accompanied by a caption that imparts valuable information.",
      "The attention to detail in the image is mirrored by the informative and well-written caption.",
      "Both visually appealing and informative, the image and its accompanying caption make a perfect pair.",
      "The creatively edited image gains appeal with an informative caption that enhances its impact.",
      "The well-edited image and its informative caption make an excellent combination.",
      "The image is flawlessly edited, and the accompanying caption offers valuable insights.",
      "The image and its accompanying caption work harmoniously to provide a comprehensive understanding of the product.",
      "The well-edited image is accompanied by a well-written and informative caption.",
      "The creatively edited image is enriched by an informative caption that offers a great overview of the product.",
      "The image and its informative caption work together to highlight the distinctive features of the product.",
      "The expertly crafted image is complemented by an accompanying caption that provides valuable information.",
      "The well-edited image and its informative caption ensure a clear understanding of the product.",
      "The creatively edited image and its accompanying caption perfectly describe the product.",
      "The beautifully edited image is accompanied by an informative caption that highlights its notable features.",
    ]
  end

  def self.good_genericwithcaptions
    [
      "The visually captivating image is accompanied by insightful captions.",
      "The image is a masterpiece that captivates, accompanied by engaging captions.",
      "Skillfully written captions perfectly complement the visually stunning image.",
      "The breathtaking image is accompanied by valuable information in the captions.",
      "The combination of the image and captions is brilliantly captivating.",
      "The visually striking image is enhanced by engaging and captivating captions.",
      "The absolutely gorgeous image is wonderfully complemented by the captions, enhancing its beauty.",
      "Thoughtfully crafted captions add depth to the meaning of the true work of art captured in the image.",
      "The image and captions together create an unforgettable impression on the viewer.",
      "The stunning image is accompanied by incredibly captivating captions.",
      "Expertly crafted captions perfectly complement the beauty of the image.",
      "The breathtaking image is contextually enriched by essential captions.",
      "The image and captions together weave a visually appealing narrative.",
      "The captivating image is accompanied by informative and intriguing captions.",
      "The impressive image gains additional meaning through its captivating captions.",
      "Skillfully written captions highlight the image's best features.",
      "The visually striking image is skillfully narrated by captivating captions.",
      "The visually pleasing image grabs the viewer's attention with its captivating captions.",
      "The image and captions form a perfect symbiosis, creating a visually stunning experience."
    ]    
  end

  def self.good_generic
    [
      "The picture is executed with skillful composition.",
      "The skillful capture is evident in the image.",
      "Excellent lighting is showcased in the photo.",
      "A superb balance of colors is demonstrated in the picture.",
      "Outstanding photography is exemplified by the photo.",
      "The subject is portrayed in a captivating manner in the image.",
      "The essence of the moment is perfectly captured in the picture.",
      "An impressive level of technical expertise is exhibited in the photo.",
      "The photographer's artistic talent is beautifully demonstrated in the image.",
      "A discerning eye for detail and composition is showcased in the picture.",
      "A compelling visual story is told by the photo.",
      "Light and shadow are skillfully employed in the image to create an impact.",
      "Powerful visuals evoke strong emotions in the picture.",
      "The art and craft of photography are represented at its finest in the photo.",
      "The image is a stunning piece of visual artistry.",
      "The message is effectively communicated through visual elements in the picture.",
      "The photographer's vision is brilliantly captured in the photo.",
      "The subject matter is powerfully represented in the image.",
      "The scene is depicted beautifully and evocatively in the picture.",
      "A striking and memorable composition leaves a lasting impression in the photo.",
      "Technical skill and artistic prowess are harmoniously combined in the image.",
      "The picture is a visually engaging work that commands attention.",
      "The subject is breathtakingly portrayed in the photo.",
      "An exceptional achievement in the field of photography is represented by the image.",
      "Outstanding visual design is exemplified in the picture.",
      "The photographer's expertise and creativity are showcased in the photo.",
      "Thoughts and emotions are sparked by the visually stunning impact of the image.",
      "Impeccable photographic composition is demonstrated in the picture.",
      "The subject matter is presented in a beautiful and compelling way in the photo.",
      "An impressive blend of technical proficiency and artistic vision is displayed in the image.",
      "A captivating visual story is vividly told by the picture.",
      "The photo captivates and resonates with its deep emotional depth.",
      "Stunning visuals portray the subject matter in the image.",
      "A poignant and evocative moment is captured in the picture.",
      "A striking and memorable visual statement is made by the photo.",
      "The work is a beautiful and haunting piece of art in the image.",
      "Form and function are seamlessly combined with mastery in the picture.",
      "Breathtaking beauty leaves a lasting impression in the photo.",
      "The stunning beauty of the natural world is showcased in the image.",
      "Creativity and technical prowess of the photographer are reflected in the picture.",
      "The subject is captivatingly and engagingly portrayed in the photo.",
      "The image is a masterful work of art that holds the viewer's attention."
    ]
  end

  def self.bad_generic
    [
      "The visual appeal is lacking in the image, and its message fails to come across.",
      "The composition of the image appears to be subpar and lacks clarity.",
      "The image lacks vibrancy and fails to inspire.",
      "The image is devoid of appeal and struggles to attract attention.",
      "The image appears devoid of purpose or meaning.",
      "The image seems to have undergone poor editing, resulting in a lack of quality.",
      "The image lacks professionalism and creativity.",
      "The image is perplexing and lacks coherence.",
      "The image lacks balance and fails to establish a clear focal point.",
      "The image has an outdated and uninteresting appearance.",
      "The image lacks depth and fails to captivate the viewer.",
      "The image seems to be a low-quality stock photograph.",
      "The image lacks artistic merit and fails to evoke any emotions.",
      "The composition of the image is haphazard and lacks visual coherence.",
      "The image is mundane and fails to leave a lasting impression.",
      "The image is unremarkable and fails to stand out from the crowd.",
      "The image lacks originality and feels derivative.",
      "The image is poorly framed and lacks a sense of purpose.",
      "The image is unimpressive and fails to showcase any technical skill.",
      "The image is forgettable and fails to make a strong visual statement.",
      "The image is disjointed and lacks a clear narrative or focal point.",
      "The image appears amateurish and lacks professional execution.",
      "The image lacks imagination and creativity, feeling clichéd.",
      "The image is disorienting and fails to communicate a coherent message.",
      "The image is visually uninteresting and lacks dynamic elements.",
      "The image appears hastily captured and lacks attention to detail.",
      "The image lacks visual impact and fails to engage the viewer.",
      "The image is uninspired and lacks artistic flair.",
      "The image is poorly lit and lacks visual depth.",
      "The image lacks composition and feels chaotic.",
      "The image is unappealing and fails to draw the viewer's eye.",
      "The image is poorly edited and lacks technical finesse.",
      "The image is uninspiring and fails to spark curiosity.",
      "The image is cluttered and lacks visual clarity.",
      "The image appears outdated and fails to resonate with modern aesthetics.",
      "The image is unmemorable and fails to leave a lasting impression.",
      "The image is generic and lacks a unique perspective.",
      "The image lacks storytelling elements and fails to engage the viewer.",
      "The image is uninteresting and fails to provoke thought or emotion.",
      "The image lacks skillful composition and feels amateurish.",
      "The image is flat and lacks depth, appearing two-dimensional.",
      "The image is poorly executed and lacks artistic intention.",
      "The image appears random and lacks a cohesive theme or concept.",
      "The image lacks visual balance and feels off-kilter.",
      "The image is uninspiring and fails to ignite the imagination.",
      "The image is unengaging and lacks a focal point of interest.",
      "The image is unpolished and lacks attention to detail.",
      "The image appears clichéd and lacks originality.",
      "The image lacks energy and fails to create a visual impact.",
      "The image is unconvincing and fails to evoke any emotional response.",
      "The image lacks technical proficiency and feels amateurish.",
      "The image is lackluster and fails to convey a sense of purpose.",
      "The image is uninspiring and fails to evoke curiosity or interest.",
      "The image is disjointed and lacks a cohesive visual narrative."
  ]
  end

  def self.bad_editing
    [
      "The image lacks originality and fails to offer anything captivating or unique.",
      "The image gives the impression of unprofessional editing, with unnatural colors and lighting.",
      "The proportions in this image appear distorted and unrealistic due to poorly executed editing.",
      "The editing on this image appears amateurish, with visible pixelation and blurriness.",
      "The image displays signs of sloppy editing, with noticeable patches and inconsistent shadows.",
      "It's evident that the editing on this image was done carelessly, resulting in a loss of detail and clarity.",
      "The image has an unpolished and unprofessional appearance due to poorly executed editing.",
      "The editing on this image seems rushed, resulting in obvious flaws and inconsistencies.",
      "It appears that the editor paid little attention to detail, as the image exhibits sloppy and unrefined edits.",
      "The image has been poorly edited, with evident errors and a lack of visual coherence.",
      "The editing on this image is subpar, showing noticeable artifacts and distortions.",
      "The editing on this image lacks precision, resulting in an unnatural and poorly blended look.",
      "The image displays visible imperfections and unnatural elements due to inadequate editing.",
      "The edits made to this image lack finesse and attention to detail, giving it a poorly edited appearance.",
      "It seems like the editor lacked sufficient skill, as the image shows evident signs of careless editing.",
      "The image has been edited without maintaining a cohesive and realistic look.",
      "The editing on this image is unconvincing, with noticeable discrepancies and a lack of visual harmony.",
      "It's apparent that the editor lacked the necessary expertise, as the image exhibits evident flaws and inconsistencies.",
      "The image has been edited in a way that compromises its quality, with visible distortions and inaccuracies.",
      "The editing on this image lacks professionalism, with visible errors and a lack of refinement.",
      "It's clear that the editor lacked the necessary skills, as the image appears poorly edited and unpolished.",
      "The image has undergone inadequate editing, resulting in an unappealing and unprofessional final result.",
      "The editing done on this image appears rushed and careless, with evident shortcomings and a lack of attention to detail.",
      "It seems like the editor had a limited understanding of image editing techniques, as the flaws are apparent.",
      "The image has been edited in a way that compromises its visual integrity, with noticeable inconsistencies and inaccuracies.",
      "The editing on this image is visibly flawed, with evident mistakes and a lack of attention to fine details.",
      "It's clear that the editing was not executed with finesse, as the image shows visible signs of hasty and unrefined edits.",
      "The image has been subjected to substandard editing, resulting in an unnatural and unpolished appearance.",
      "The edits made to this image lack professionalism, with noticeable discrepancies and a lack of visual cohesion.",
      "It seems like the editor lacked the necessary expertise and attention to detail, as the image displays visible flaws and inconsistencies."
    ]
  end

end
