class Video

	def self.good_editing
		[
			"The craftsmanship and visuals in this video are absolutely amazing.",
			"The creative editing of this video is truly impressive and holds your attention.",
			"This video pays incredible attention to detail, making it a visual masterpiece.",
			"The story in this video is expertly conveyed through captivating visual storytelling.",
			"The editing in this video is seamless and professional, creating a true work of art.",
			"The visuals in this video are stunning and leave a lasting impression.",
			"Both the cinematography and editing in this video are captivating and skillfully executed.",
			"The use of music and sound effects in this video is exceptional, greatly enhancing its impact.",
			"This video is a testament to the creativity and talent of its creators.",
			"The use of color, light, and shadow in this video is absolutely breathtaking.",
			"The editing and pacing in this video are executed perfectly, making it a joy to watch.",
			"The imagery in this video is both beautiful and thought-provoking, leaving a lasting impression.",
			"This video's visual storytelling is exceptional and demonstrates the power of the medium.",
			"The special effects and editing in this video are truly impressive and skillfully done.",
			"The creative use of camera angles and lighting in this video is both effective and imaginative.",
			"The production quality of this video is exceptional, showcasing meticulous attention to detail.",
			"The editing of this video is so smooth and professional that it's hard to take your eyes off it.",
			"The visuals in this video are thoughtfully composed and executed with beauty.",
			"The combination of live-action and animation in this video is seamlessly integrated, resulting in an engaging and impactful experience.",
			"The video has been edited by experts, showcasing their professional craftsmanship.",
			"The editing in this video is exceptional, capturing the essence and core of the content.",
			"The edited video is a masterpiece, with flawless transitions and captivating visuals.",
			"The video editing is top-notch, enhancing the storytelling and viewer engagement.",
			"The editing of this video is superb, elevating its impact and quality.",
			"The edited video is a work of art, showcasing the editor's skill and creative flair.",
			"The video editing is outstanding, creating a visually stunning and cohesive viewing experience.",
			"The editing in this video is masterful, effectively conveying the intended message and emotions.",
			"The edited video is impressive, with polished editing and a seamless flow.",
			"The video has been flawlessly edited, resulting in a visually captivating and immersive experience.",
			"The editing of this video is remarkable, bringing out the best in every frame.",
			"The edited video is a testament to excellent editing, with impeccable attention to detail and coherence.",
			"The video editing is stellar, enhancing the narrative and visual appeal to a remarkable degree.",
			"The editing in this video is sublime, showcasing a perfect balance of elements and aesthetics.",
			"The edited video is a triumph of editing, with smooth transitions and impeccable timing that keeps you engaged.",
			"The video has been expertly edited, resulting in a polished and professional outcome.",
			"The editing of this video is outstanding, displaying artistic vision and technical expertise at its finest.",
			"The video editing is exceptional, creating a visually stunning and emotionally impactful experience.",
			"The editing in this video is first-rate, delivering a cohesive and engaging story with precision.",
			"The edited video is a masterpiece of editing, with each scene seamlessly flowing into the next, creating a harmonious whole.",
			"The video has been meticulously edited, resulting in a visually striking and immersive experience that draws you in.",
			"The editing of this video is sublime, showcasing the editor's talent and creative vision in every frame.",	
	    'The editing work of genius, with precise editing choices and impeccable timing that elevate its brilliance.",
			"The video editing is top-notch, elevating the content to new heights of excellence and impact.",
			"The editing in this video is remarkable, effectively conveying the intended emotions and messages with utmost clarity.",
			"The edited video is a testament to exceptional editing skills, with seamless transitions and captivating visuals that leave a lasting impression.",
			"The video has been flawlessly edited, resulting in a cinematic experience that captivates and lingers in your memory.",
			"The editing of this video is extraordinary, seamlessly bringing together disparate elements into a cohesive and compelling whole.",
			"The edited video is a triumph of editing, with impeccable attention to detail and narrative coherence that keeps you invested.",
			"The video editing is stellar, enhancing the storytelling and immersing the viewer in the content with great finesse.",
			"The editing in this video is top-tier, displaying a perfect balance of pacing, visual aesthetics, and narrative impact.",
			"The edited video is a shining example of excellent editing, with each shot perfectly composed and timed for maximum impact.",
			"The video has been expertly edited, resulting in a visually stunning and emotionally resonant experience that touches your heart.",
			"The editing of this video is outstanding, showcasing the editor's artistic prowess and technical finesse in every frame.",
			"The edited video is a masterpiece, with flawless editing choices that enhance the impact and depth of each scene.",
			"The video editing is exceptional, creating a seamless and engaging flow that holds the viewer's attention from start to finish.",
			"The editing in this video is sublime, effectively capturing the essence of the subject matter and delivering a powerful message.",
			"The edited video is a work of art, with impeccable editing that brings out the best in every frame, evoking strong emotions.",
			"The video showcases exceptional craftsmanship and mesmerizing visuals.",
			"The creative editing of this video is truly impressive and holds your attention throughout.",
			"This video pays meticulous attention to detail, making it a visual masterpiece.",
			"The story is expertly told through masterful visual storytelling in this video.",
			"The editing in this video is seamless and professional, creating a true work of art.",
			"The visuals in this video are breathtaking, leaving a lasting impact on the viewer.",
			"Both the cinematography and editing in this video are captivating and skillfully executed.",
			"The use of music and sound effects in this video is exceptional, adding to its overall impact.",
			"This video is a true testament to the creativity and talent of its makers.",
			"The use of color, light, and shadow in this video is absolutely stunning.",
			"The editing and pacing in this video are executed perfectly, making it a joy to watch.",
			"The imagery in this video is both beautiful and thought-provoking, leaving a lasting impression.",
			"This video's visual storytelling is exceptional and demonstrates the power of the medium.",
			"The special effects and editing in this video are truly impressive and skillfully executed.",
			"The use of camera angles and lighting in this video is both creative and effective.",
			"The production quality of this video is exceptional, showcasing meticulous attention to detail.",
			"The editing of this video is so seamless and professional, it's hard to look away.",
			"The visuals in this video are thoughtfully composed and beautifully executed.",
			"The combination of live-action and animation in this video is seamlessly integrated, resulting in an engaging and effective video.",
			"The video has been edited by experts, showcasing their professional craftsmanship.",
			"The editing in this video is exceptional, capturing the essence and core of the content.",
			"The edited video is a masterpiece, with flawless transitions and captivating visuals.",
			"The video editing is top-notch, enhancing the storytelling and keeping the audience engaged.",
			"The editing of this video is superb, elevating its impact and overall quality.",
			"The edited video is a work of art, showcasing the editor's skill, creativity, and attention to detail.",
			"The video editing is outstanding, creating a visually stunning and cohesive experience.",
			"The editing in this video is masterful, effectively conveying the intended message with precision.",
			"The edited video is impressive, with polished editing and a seamless flow that keeps you hooked.",
			"The video has been flawlessly edited, resulting in a visually captivating experience that grabs your attention.",
			"The editing of this video is remarkable, bringing out the best in each frame and emphasizing its beauty.",
			"The edited video is a testament to excellent editing, with impeccable attention to detail and overall craftsmanship.",
			"The video editing is stellar, enhancing the narrative and visual appeal to create an immersive experience.",
			"The editing in this video is sublime, showcasing a perfect balance of elements and creating a mesmerizing effect.",
			"The edited video is a triumph of editing, with smooth transitions and impeccable timing that enhances its impact.",
			"The video has been expertly edited, resulting in a polished and professional outcome that is visually stunning.",
			"The editing of this video is outstanding, displaying artistic vision and technical expertise at its finest.",
			"The video editing is exceptional, creating a visually stunning and emotionally impactful experience that resonates deeply.",
			"The editing in this video is first-rate, delivering a cohesive and engaging story with precision and finesse.",
			"The edited video is a masterpiece of editing, with each scene seamlessly flowing into the next, creating a captivating journey.",
			"The video has been meticulously edited, resulting in a visually striking and immersive experience that transports you."
		]
	end

	def self.good_generic
		[
			"The video editing is impressive, incorporating crisp editing techniques and a creative approach.",
			"This video captures your attention with its engaging content, high production value, and captivating visuals.",
			"The video stands out with outstanding editing, showcasing professional editing skills and seamless transitions.",
			"This video is top-notch, featuring a polished presentation and compelling storytelling that keeps you engaged.",
			"The video is excellent, displaying skilled cinematography and a well-crafted narrative that leaves a lasting impact.",
			"This video is remarkable, characterized by a unique style and meticulous attention to detail that sets it apart.",
			"The video is captivating, with a professional voiceover and visually appealing graphics that draw you in.",
			"This video is exceptional, demonstrating creativity and professionalism in its execution.",
			"The video is impressive, with a well-executed script and dynamic pacing that holds your interest.",
			"This video is outstanding, delivering clear audio and visually pleasing aesthetics that enhance the viewing experience.",
			"The video is fantastic, with high-quality visuals and a cohesive storyline that keeps you hooked.",
			"This video is engaging, thanks to seamless editing techniques and impactful visuals that leave a strong impression.",
			"The video is remarkable, featuring expert direction and a powerful message that resonates deeply.",
			"This video is excellent, presenting a compelling narrative and showcasing skilled execution throughout.",
			"The video is outstanding, characterized by professional-grade production values and meticulous attention to detail.",
			"This video is exceptional, seamlessly blending visuals and audio to create a captivating experience.",
			"The video is impressive, with creative editing techniques and strong visual storytelling that leave a lasting impression.",
			"This video is captivating, with a well-written script and engaging narration that keeps you engrossed.",
			"The video is fantastic, boasting professional-grade animation and a captivating storyline that captivates the audience.",
			"This video is remarkable, featuring a well-structured narrative and impressive visuals that leave a lasting impact.",
			"The video is excellent, with professional-grade cinematography and a compelling soundtrack that enhances the overall experience.",
			"This video is outstanding, presenting a cohesive storyline and stunning visuals that make it truly memorable.",
			"The video is exceptional, showcasing polished editing techniques and a well-executed concept that elevates its quality.",
			"This video is impressive, offering engaging visuals and a powerful emotional impact that resonates with the viewer.",
			"The video is captivating, thanks to seamless transitions and professional-grade production values that enhance the viewing experience.",
			"This video is fantastic, displaying impressive attention to detail and skilled storytelling techniques that make it stand out.",
			"The video is remarkable, striking a well-balanced mix of information and entertainment that keeps you engaged.",
			"This video is excellent, featuring a strong script and visually appealing graphics that enhance its presentation.",
			"The video is outstanding, with professional-grade editing and a compelling voiceover that immerses you in the content.",
			"This video is exceptional, with dynamic visuals and a well-paced storyline that keeps you invested throughout.",
			"The video is impressive, showcasing professional-grade animation and a captivating script that captures your attention.",
			"This video is captivating, offering engaging storytelling and visually stunning effects that create an immersive experience.",
			"The video is fantastic, characterized by well-choreographed scenes and high production quality that make it visually appealing.",
			"This video is remarkable, with a well-designed concept and meticulous attention to detail that enhance its overall impact.",
			"The video is excellent, featuring professional-grade cinematography and a compelling narrative that captivates the audience.",
			"This video is outstanding, with seamless editing techniques and a powerful emotional impact that resonates with viewers.",
			"The video is exceptional, showcasing polished visuals and a well-executed storyline that
	 leaves a lasting impression.",
			"This video is impressive, delivering engaging content and high production value that keeps you hooked.",
			"The video is captivating, featuring professional-grade editing and visually striking imagery that grabs your attention.",
			"This video is fantastic, with a well-crafted script and a captivating voiceover that adds depth to the visuals.",
			"The video is remarkable, boasting high-quality graphics and a compelling storyline that makes it truly memorable.",
			"This video is excellent, with seamless transitions and a polished presentation that enhances the overall viewing experience.",
			"The video is outstanding, characterized by professional-grade production values and meticulous attention to detail.",
			"This video is exceptional, demonstrating creative direction and impressive visuals that leave a lasting impact.",
			"The video is impressive, with skilled editing techniques and a well-structured narrative that keeps you engaged.",
			"This video is captivating, featuring a compelling voiceover and visually appealing aesthetics that enhance the viewing experience."
	]
		end

	def self.good_generic_product
		[
			"The video has done an excellent job of explaining the product's features in a clear and concise manner.",
			"This video is highly effective in presenting and explaining the product's features with great clarity.",
			"The video has done a remarkable job of showcasing and explaining the various features of the product.",
			"This video excels in explaining the product's features, leaving no room for confusion or ambiguity.",
			"The video has successfully communicated the features of the product in a comprehensive and understandable way.",
			"This video is praiseworthy for its ability to explain the product's features with precision and simplicity.",
			"The video has done a fantastic job of breaking down and explaining each feature of the product.",
			"This video is commendable for its clear and thorough explanation of the product's features.",
			"The video has effectively highlighted and explained the key features of the product with great expertise.",
			"This video deserves credit for its concise and informative presentation of the product's features.",
			"The video has done an outstanding job of elucidating the features of the product in a concise manner.",
			"This video impressively explains the product's features, making it easy for viewers to understand.",
			"The video has skillfully demonstrated and explained the features of the product, leaving no questions unanswered.",
			"This video deserves recognition for its ability to present and explain the product's features in a compelling way.",
			"The video has done an exceptional job of articulating and illustrating the product's features effectively.",
			"This video is praiseworthy for its clear and engaging explanation of the product's features.",
			"The video has successfully showcased and explained the product's features with great attention to detail.",
			"This video stands out for its ability to explain the product's features in a concise and user-friendly manner.",
			"The video has done a fantastic job of presenting and explaining the key features of the product.",
			"This video deserves appreciation for its thorough and easy-to-understand explanation of the product's features.",
			"The video has effectively communicated the features of the product, ensuring a solid understanding for the viewers.",
			"This video excels in explaining the product's features, providing valuable insights to potential customers.",
			"The video has skillfully explained each feature of the product, making it accessible to a wide range of viewers.",
			"This video is praiseworthy for its informative and engaging presentation of the product's features.",
			"The video has done an exceptional job of outlining and explaining the product's features with great clarity.",
			"This video deserves recognition for its comprehensive and well-structured explanation of the product's features.",
			"The video has successfully highlighted and explained the key features of the product in an easily digestible way.",
			"This video impressively explains the product's features, ensuring that viewers grasp their significance.",
			"The video has skillfully demonstrated and explained the features of the product, making it an informative resource for viewers.",
			"This video stands out for its ability to present and explain the product's features in a concise and impactful manner.",
			"The video has done a fantastic job of showcasing and explaining the unique features of the product.",
			"This video deserves appreciation for its clear and comprehensive explanation of the product's features.",
			"The video has effectively communicated the features of the product, providing viewers with valuable insights.",
			"This video excels in explaining the product's features, making it easy for potential customers to understand.",
			"The video has skillfully outlined and explained each feature of the product, ensuring viewers are well-informed.",
		]
	end

	def self.bad_graphics
		[
			"The video graphics quality is below average.",
			"The graphics in the video are poorly executed.",
			"The video's visual effects are lacking in quality.",
			"The graphics in the video are not up to par.",
			"The video's visuals are unimpressive.",
			"The graphics in the video are of poor quality.",
			"The video's graphics are subpar.",
			"The visuals in the video are not up to the mark.",
			"The video's graphics are not very appealing.",
			"The video's graphics are not very engaging.",
			"The video's graphics are not very captivating.",
			"The video's graphics are not very impressive.",
			"The video's graphics are not very eye-catching.",
			"The video's graphics are not very attention-grabbing.",
			"The video's graphics leave much to be desired.",
			"The graphics in the video are outdated.",
			"The video's graphics are lackluster.",
			"The video's graphics are unprofessional.",
			"The graphics in the video are unappealing.",
			"The video's graphics are dull and uninspiring."
		]
	end

	def self.bad_editing
		[
		  "The video editing seems choppy and unprofessional.",
		  "The editing is sloppy and doesn't flow well.",
		  "The video appears to have been edited hastily and without care.",
		  "The editing looks amateurish and lacking in finesse.",
		  "The video has been edited in a way that feels disjointed.",
		  "The editing doesn't effectively convey the intended message.",
		  "The editing detracts from the overall quality of the video.",
		  "The video editing is lacking in polish and refinement.",
		  "The video feels off due to poor editing choices.",
		  "The editing is lazy and doesn't do justice to the footage.",
		  "The video has been edited in a way that feels disorienting.",
		  "The editing is subpar and undermines the impact of the video.",
		  "The video editing lacks cohesion and clarity.",
		  "The editing choices feel random and don't serve a clear purpose.",
		  "The editing makes it difficult to follow the story or message.",
		  "The video editing looks unpolished and unrefined.",
		  "The video was poorly edited and lacks quality.",
		  "The editing is sloppy, affecting the video's overall impact.",
		  "It's clear the video was poorly edited, compromising its quality.",
		  "The editing falls short, hindering the video's effectiveness.",
		  "The video's poor editing undermines its message.",
		  "It's evident the video has been poorly edited and lacks finesse.",
		  "The editing is subpar, diminishing the video's value.",
		  "The video suffers from amateurish editing, hindering its appeal.",
		  "The editing is unimpressive and fails to captivate.",
		  "It's apparent the video's editing is below par, impacting its quality.",
		  "The video's editing is lacking, resulting in a disappointing experience.",
		  "It's clear the video was haphazardly edited, impacting its coherence.",
		  "The editing quality is unsatisfactory, detracting from the video's impact.",
		  "The video's editing is flawed, compromising its overall effectiveness.",
		  "The video suffers from substandard editing, hindering its success.",
		  "It's apparent the video's editing is lackluster, leaving much to be desired.",
		  "The editing quality falls short, diminishing the video's appeal.",
		  "The video's editing is subpar, failing to meet expectations.",
		  "It's clear the video was poorly edited, resulting in an underwhelming outcome.",
		  "The editing is careless, affecting the video's overall quality.",
		  "The video's editing is below standard, compromising its effectiveness.",
		  "It's evident the video was haphazardly edited, lacking finesse.",
		  "The editing quality is disappointing, detracting from the video's impact.",
		  "The video's editing is flawed, hindering its success.",
		  "It's apparent the video's editing is unimpressive, lacking cohesion.",
		  "The editing is substandard, impacting the video's overall quality.",
		  "The video suffers from lackluster editing, diminishing its appeal.",
		  "It's clear the video was poorly edited, affecting its pacing.",
		  "The editing is unskilled, failing to engage the audience effectively.",
		  "The video's editing is subpar, leaving much to be desired.",
		  "It's evident the video was poorly edited, resulting in a lack of coherence.",
		  "The editing quality falls short, compromising the video's impact.",
		  "The video's editing is careless, hindering its overall effectiveness.",
		  "It's apparent the video's editing is below standard, lacking finesse.",
		  "The editing is disappointing, detracting from the video's quality.",
		  "The video's editing is flawed, resulting in an underwhelming outcome.",
		  "It's evident the video was haphazardly edited, lacking professionalism.",
		  "The video's editing is substandard, failing to meet expectations.",
		  "It's clear the video was poorly edited, diminishing its overall quality."
		]
	end
end