class Video

	def self.good_editing
		[
			"The video showcases exceptional craftsmanship and stunning visuals.",
			"The creative editing of this video is truly impressive and captivating.",
			"This video pays great attention to detail, making it a visual masterpiece.",
			"The story is expertly told through this video's masterful visual storytelling.",
			"The seamless and professional editing in this video makes it a true work of art.",
			"The visuals in this video are breathtaking, leaving a lasting impression on the viewer.",
			"The cinematography and editing of this video are truly captivating and skillfully executed.",
			"The use of music and sound effects in this video is exceptional, adding to its overall impact.",
			"This video is a true testament to the creativity and talent of its makers.",
			"The use of color, light, and shadow in this video is absolutely stunning.",
			"The editing and pacing in this video are perfectly executed, making it a joy to watch.",
			"The imagery in this video is both beautiful and thought-provoking, leaving a lasting impression.",
			"This video's exceptional visual storytelling is a testament to the power of the medium.",
			"The special effects and editing in this video are truly impressive and skillfully executed.",
			"The use of camera angles and lighting in this video is both creative and effective.",
			"The production quality of this video is exceptional, showcasing great attention to detail.",
			"The editing of this video is so seamless and professional, it's hard to look away.",
			"The visuals in this video are thoughtfully composed and beautifully executed.",
			"The combination of live-action and animation in this video is seamlessly integrated, resulting in an engaging and effective video.",
			"The video has been expertly edited, showcasing professional craftsmanship.",
			"The editing in this video is exceptional, capturing the essence of the content.",
			"The edited video is a masterpiece, with seamless transitions and captivating visuals.",
			"The video editing is top-notch, enhancing the storytelling and engagement.",
			"The editing of this video is superbly done, elevating its impact and quality.",
			"The edited video is a work of art, showcasing the editor's skill and creativity.",
			"The video editing is outstanding, creating a visually stunning and cohesive experience.",
			"The editing in this video is masterful, effectively conveying the intended message.",
			"The edited video is impressive, with polished editing and seamless flow.",
			"The video has been flawlessly edited, resulting in a visually captivating experience.",
			"The editing of this video is remarkable, bringing out the best in each frame.",
			"The edited video is a testament to excellent editing, with impeccable attention to detail.",
			"The video editing is stellar, enhancing the narrative and visual appeal.",
			"The editing in this video is sublime, showcasing a perfect balance of elements.",
			"The edited video is a triumph of editing, with smooth transitions and impeccable timing.",
			"The video has been expertly edited, resulting in a polished and professional outcome.",
			"The editing of this video is outstanding, displaying artistic vision and technical expertise.",
			"The video editing is exceptional, creating a visually stunning and emotionally impactful experience.",
			"The editing in this video is first-rate, delivering a cohesive and engaging story.",
			"The edited video is a masterpiece of editing, with each scene seamlessly flowing into the next.",
			"The video has been meticulously edited, resulting in a visually striking and immersive experience.",
			"The editing of this video is sublime, showcasing the editor's talent and creative vision.",
			"The edited video is a work of genius, with precise editing choices and impeccable timing.",
			"The video editing is top-notch, elevating the content to new heights of excellence.",
			"The editing in this video is remarkable, effectively conveying the intended emotions and messages.",
			"The edited video is a testament to exceptional editing skills, with seamless transitions and captivating visuals.",
			"The video has been flawlessly edited, resulting in a cinematic experience that leaves a lasting impression.",
			"The editing of this video is extraordinary, bringing together disparate elements into a cohesive whole.",
			"The edited video is a triumph of editing, with impeccable attention to detail and narrative coherence.",
			"The video editing is stellar, enhancing the storytelling and immersing the viewer in the content.",
			"The editing in this video is top-tier, displaying a perfect balance of pacing and visual aesthetics.",
			"The edited video is a shining example of excellent editing, with each shot perfectly composed and timed.",
			"The video has been expertly edited, resulting in a visually stunning and emotionally resonant experience.",
			"The editing of this video is outstanding, showcasing the editor's artistic prowess and technical finesse.",
			"The edited video is a masterpiece, with flawless editing choices that enhance the impact of each scene.",
			"The video editing is exceptional, creating a seamless and engaging flow that holds the viewer's attention.",
			"The editing in this video is sublime, effectively capturing the essence of the subject matter and delivering a powerful message.",
			"The edited video is a work of art, with impeccable editing that brings out the best in every frame.",
		]
	end

		self.good_generic
		[
			"The video is impressive, with crisp editing and a creative approach.",
			"This video is engaging, with high production value and captivating visuals.",
			"The video is outstanding, showcasing professional editing and seamless transitions.",
			"This video is top-notch, with a polished presentation and compelling storytelling.",
			"The video is excellent, featuring skilled cinematography and a well-crafted narrative.",
			"This video is remarkable, with a unique style and attention to detail.",
			"The video is captivating, with a professional voiceover and visually appealing graphics.",
			"This video is exceptional, demonstrating creativity and professionalism.",
			"The video is impressive, with a well-executed script and dynamic pacing.",
			"This video is outstanding, with clear audio and visually pleasing aesthetics.",
			"The video is fantastic, with high-quality visuals and a cohesive storyline.",
			"This video is engaging, with seamless editing and impactful visuals.",
			"The video is remarkable, with expert direction and a powerful message.",
			"This video is excellent, with a compelling narrative and skilled execution.",
			"The video is outstanding, with professional-grade production and attention to detail.",
			"This video is exceptional, with a seamless blend of visuals and audio.",
			"The video is impressive, with creative editing and strong visual storytelling.",
			"This video is captivating, with a well-written script and engaging narration.",
			"The video is fantastic, with professional-grade animation and a captivating storyline.",
			"This video is remarkable, with a well-structured narrative and impressive visuals.",
			"The video is excellent, with professional-grade cinematography and a compelling soundtrack.",
			"This video is outstanding, with a cohesive storyline and stunning visuals.",
			"The video is exceptional, with polished editing and a well-executed concept.",
			"This video is impressive, with engaging visuals and a powerful emotional impact.",
			"The video is captivating, with seamless transitions and professional-grade production.",
			"This video is fantastic, with impressive attention to detail and skilled storytelling.",
			"The video is remarkable, with a well-balanced mix of information and entertainment.",
			"This video is excellent, with a strong script and visually appealing graphics.",
			"The video is outstanding, with professional-grade editing and a compelling voiceover.",
			"This video is exceptional, with dynamic visuals and a well-paced storyline.",
			"The video is impressive, with professional-grade animation and a captivating script.",
			"This video is captivating, with engaging storytelling and visually stunning effects.",
			"The video is fantastic, with well-choreographed scenes and high production quality.",
			"This video is remarkable, with a well-designed concept and attention to detail.",
			"The video is excellent, with professional-grade cinematography and a compelling narrative.",
			"This video is outstanding, with seamless editing and a powerful emotional impact.",
			"The video is exceptional, with polished visuals and a well-executed storyline.",
			"This video is impressive, with engaging content and high production value.",
			"The video is captivating, with professional-grade editing and visually striking imagery.",
			"This video is fantastic, with a well-crafted script and a captivating voiceover.",
			"The video is remarkable, with high-quality graphics and a compelling storyline.",
			"This video is excellent, with seamless transitions and a polished presentation.",
			"The video is outstanding, with professional-grade production and attention to detail.",
			"This video is exceptional, with creative direction and impressive visuals.",
			"The video is impressive, with skilled editing and a well-structured narrative.",
			"This video is captivating, with a compelling voiceover and visually appealing aesthetics.",
		]
		end

	def self.bad_graphics
		[
		  "The video graphics quality is below average.",
		  "The graphics in the video are poorly executed.",
		  "The video's visual effects are lacking in quality.",
		  "The graphics in the video are not up to par.",
		  "The video's visuals are unimpressive.",
		  "The graphics in the video are of poor quality.",
		  "The video's graphics are subpar.",
		  "The visuals in the video are not up to the mark.",
		  "The video's graphics are not very appealing.",
		  "The video's graphics are not very engaging.",
		  "The video's graphics are not very captivating.",
		  "The video's graphics are not very impressive.",
		  "The video's graphics are not very eye-catching.",
		  "The video's graphics are not very attention-grabbing.",
		  "The video's graphics leave much to be desired.",
		  "The graphics in the video are outdated.",
		  "The video's graphics are lackluster.",
		  "The video's graphics are unprofessional.",
		  "The graphics in the video are unappealing.",
		  "The video's graphics are dull and uninspiring."
		]
	end

	def self.bad_editing
		[
		  "The video editing seems choppy and unprofessional.",
		  "The editing is sloppy and doesn't flow well.",
		  "The video appears to have been edited hastily and without care.",
		  "The editing looks amateurish and lacking in finesse.",
		  "The video has been edited in a way that feels disjointed.",
		  "The editing doesn't effectively convey the intended message.",
		  "The editing detracts from the overall quality of the video.",
		  "The video editing is lacking in polish and refinement.",
		  "The video feels off due to poor editing choices.",
		  "The editing is lazy and doesn't do justice to the footage.",
		  "The video has been edited in a way that feels disorienting.",
		  "The editing is subpar and undermines the impact of the video.",
		  "The video editing lacks cohesion and clarity.",
		  "The editing choices feel random and don't serve a clear purpose.",
		  "The editing makes it difficult to follow the story or message.",
		  "The video editing looks unpolished and unrefined."
		  "The video was poorly edited and lacks quality.",
		  "The editing is sloppy, affecting the video's overall impact.",
		  "It's clear the video was poorly edited, compromising its quality.",
		  "The editing falls short, hindering the video's effectiveness.",
		  "The video's poor editing undermines its message.",
		  "It's evident the video has been poorly edited and lacks finesse.",
		  "The editing is subpar, diminishing the video's value.",
		  "The video suffers from amateurish editing, hindering its appeal.",
		  "The editing is unimpressive and fails to captivate.",
		  "It's apparent the video's editing is below par, impacting its quality.",
		  "The video's editing is lacking, resulting in a disappointing experience.",
		  "It's clear the video was haphazardly edited, impacting its coherence.",
		  "The editing quality is unsatisfactory, detracting from the video's impact.",
		  "The video's editing is flawed, compromising its overall effectiveness.",
		  "The video suffers from substandard editing, hindering its success.",
		  "It's apparent the video's editing is lackluster, leaving much to be desired.",
		  "The editing quality falls short, diminishing the video's appeal.",
		  "The video's editing is subpar, failing to meet expectations.",
		  "It's clear the video was poorly edited, resulting in an underwhelming outcome.",
		  "The editing is careless, affecting the video's overall quality.",
		  "The video's editing is below standard, compromising its effectiveness.",
		  "It's evident the video was haphazardly edited, lacking finesse.",
		  "The editing quality is disappointing, detracting from the video's impact.",
		  "The video's editing is flawed, hindering its success.",
		  "It's apparent the video's editing is unimpressive, lacking cohesion.",
		  "The editing is substandard, impacting the video's overall quality.",
		  "The video suffers from lackluster editing, diminishing its appeal.",
		  "It's clear the video was poorly edited, affecting its pacing.",
		  "The editing is unskilled, failing to engage the audience effectively.",
		  "The video's editing is subpar, leaving much to be desired.",
		  "It's evident the video was poorly edited, resulting in a lack of coherence.",
		  "The editing quality falls short, compromising the video's impact.",
		  "The video's editing is careless, hindering its overall effectiveness.",
		  "It's apparent the video's editing is below standard, lacking finesse.",
		  "The editing is disappointing, detracting from the video's quality.",
		  "The video's editing is flawed, resulting in an underwhelming outcome.",
		  "It's evident the video was haphazardly edited, lacking professionalism.",
		  "The editing quality is unsatisfactory, impacting the video's success.",
		  "The video's editing is substandard, failing to meet expectations.",
		  "It's clear the video was poorly edited, diminishing its overall quality."
		]
	end

end